# Generated by Django 6.0.3 on 2026-04-07 16:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
