# Generated by Django 6.0.3 on 2026-03-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final')], default='midterm', max_length=50),
        ),
    ]
