# Generated by Django 6.0.3 on 2026-03-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_paper_paper_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='name',
        ),
    ]
