# Generated by Django 6.0.3 on 2026-04-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_course_slug'),
    ]

    operations = [
    ]
